MODULE pot_param
  !
  USE nrtype
  !
  IMPLICIT NONE
  !
  ! MPARAM -> MAXIMUM NUMBER OF POTENTIAL PARAMETERS
  INTEGER(KIND = I4B), PARAMETER :: MPARAM = 5
  ! POTENTIAL PARAMETER VALUES AND UNITS
  REAL(KIND = DP), DIMENSION(1:MPARAM) :: param_pot
  !
  !
END MODULE pot_param
